Console.Write("Введите число А: ");
string numberA = Console.ReadLine();
Console.Write("Введите число B: ");
string numberB = Console.ReadLine();
Console.Write("Введите число C: ");
string numberC = Console.ReadLine();
Console.Write("Введите число D: ");
string numberD = Console.ReadLine();
Console.Write("Введите число E: ");
string numberE = Console.ReadLine();
Console.WriteLine(numberA);
Console.WriteLine(numberB);
Console.WriteLine(numberC);
Console.WriteLine(numberD);
Console.WriteLine(numberE);
